### ISSUE TITLE
et 命令报错

### ISSUE THREAD

**Issue by ay8yt** [ElementUI/element-theme#107]
node版本  v14.5.0

`npm i element-theme -g`
`npm i element-theme-chalk -D`
`et -i`

报错信息
fs.js:40
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:40:5
    at req_ (C:\Users\Gabriel\AppData\Roaming\npm\node_modules\element-theme\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\Gabriel\AppData\Roaming\npm\node_modules\element-theme\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\Gabriel\AppData\Roaming\npm\node_modules\element-theme\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)

**Comment by nangongpo** [comment]
node >= 14  
element-theme 换 element-theme-replace
