### ISSUE TITLE
初始化文件成功,但是编译不成功

### ISSUE THREAD

**Issue by BillionChen** [ElementUI/element-theme#17]
初始化文件成功,但是编译不成功

已经npm update 过了

billsMBP:www bill$ node_modules/.bin/et -i

✔ Generator variables file

billsMBP:www bill$ npm run theme-once

> www@1.0.0 theme-once /Users/workplace/www
> et -o ./src/assets/theme

✔ build theme font
[10:04:31] gulp-postcss: autocomplete.css
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/input.css:129:7: variable '--color-dark-white' is undefined and used without a fallback
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/input.css:130:7: variable '--color-light-silver' is undefined and used without a fallback
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/autocomplete.css:35:7: variable '--color-extra-light-black' is undefined and used without a fallback
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/autocomplete.css:53:9: variable '--color-base-gray' is undefined and used without a fallback
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/autocomplete.css:18:7: variable '--color-base-gray' is undefined and used without a fallback
⠸ build element theme[10:04:31] gulp-postcss: breadcrumb.css
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/breadcrumb.css:13:7: variable '--color-extra-light-silver' is undefined and used without a fallback
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/breadcrumb.css:34:13: variable '--color-light-silver' is undefined and used without a fallback
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/breadcrumb.css:21:11: variable '--color-extra-light-black' is undefined and used without a fallback
⠼ build element theme[10:04:31] gulp-postcss: button.css
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/button.css:89:11: variable '--color-base-gray' is undefined and used without a fallback
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/button.css:90:11: variable '--color-extra-light-silver' is undefined and used without a fallback
⠴ build element theme[10:04:31] gulp-postcss: cascader.css
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/input.css:129:7: variable '--color-dark-white' is undefined and used without a fallback
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/input.css:130:7: variable '--color-light-silver' is undefined and used without a fallback
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/cascader.css:48:9: variable '--color-light-silver' is undefined and used without a fallback
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/cascader.css:127:9: variable '--select-option-disabled-background' is undefined and used without a fallback
⠧ build element theme[10:04:31] gulp-postcss: color-picker.css
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/color-picker.css:165:7: variable '--color-base-black' is undefined and used without a fallback
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/color-picker.css:260:7: variable '--color-base-gray' is undefined and used without a fallback
⠇ build element theme[10:04:32] gulp-postcss: date-picker.css
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/date-picker/picker-panel.css:106:5: variable '--color-dark-white' is undefined and used without a fallback
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/date-picker/time-picker.css:78:7: variable '--color-base-silver' is undefined and used without a fallback
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/input.css:129:7: variable '--color-dark-white' is undefined and used without a fallback
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/input.css:130:7: variable '--color-light-silver' is undefined and used without a fallback
⠏ build element theme[10:04:32] gulp-postcss: dialog.css
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/dialog.css:58:7: variable '--color-base-black' is undefined and used without a fallback
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/dialog.css:63:7: variable '--color-extra-light-black' is undefined and used without a fallback
[10:04:32] gulp-postcss: dropdown.css
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/button.css:89:11: variable '--color-base-gray' is undefined and used without a fallback
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/button.css:90:11: variable '--color-extra-light-silver' is undefined and used without a fallback
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/dropdown.css:9:5: variable '--color-extra-light-black' is undefined and used without a fallback
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/dropdown.css:31:5: variable '--color-base-gray' is undefined and used without a fallback
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/dropdown.css:66:9: variable '--color-extra-light-silver' is undefined and used without a fallback
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/dropdown.css:54:9: variable '--color-base-gray' is undefined and used without a fallback
⠋ build element theme[10:04:32] gulp-postcss: form.css
postcss-custom-properties: /Users/workplace/www/node_modules/element-theme-default/src/form.css:53:7: variable '--color-extra-light-black' is undefined and used without a fallback
⠼ build element theme

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: /Users/workplace/www/node_modules/element-theme-default/src/upload.css:73:7: Unable to parse color from string "var(--color-extra-light-silver)"
    at /Users/workplace/www/node_modules/element-theme-default/src/upload.css:73:7
    at Object.Color (/Users/workplace/www/node_modules/color/index.js:34:10)
    at Color (/Users/workplace/www/node_modules/color/index.js:11:10)
    at rgba (/Users/workplace/www/node_modules/postcss-sass-color-functions/index.js:19:12)
    at handleFunction (/Users/workplace/www/node_modules/postcss-sass-color-functions/index.js:111:25)
    at /Users/workplace/www/node_modules/postcss-sass-color-functions/index.js:80:16
    at Object.tryCatch [as try] (/Users/workplace/www/node_modules/postcss-message-helpers/index.js:53:12)
    at transformDecl (/Users/workplace/www/node_modules/postcss-sass-color-functions/index.js:79:31)
    at /Users/workplace/www/node_modules/postcss/lib/container.js:192:28
    at /Users/workplace/www/node_modules/postcss/lib/container.js:148:26
    at Rule.each (/Users/workplace/www/node_modules/postcss/lib/container.js:114:22)

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "theme-once"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! www@1.0.0 theme-once: `et -o ./src/assets/theme`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the www@1.0.0 theme-once script 'et -o ./src/assets/theme'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the www package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     et -o ./src/assets/theme
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs www
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls www
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/workplace/www/npm-debug.log

**Comment by panxiuqing** [comment]
`et -i` 生成的文件是老的，不包含新使用的变量。
@QingWei-Li

**Comment by hunter007** [comment]
有没有解决方案？

**Comment by fangcao7618** [comment]
解决方案有了哇，我试了新的可以了
